vich_uploader:
    db_driver: orm
    mappings:
        logo_site:
            uri_prefix:         /uploads/site
            upload_destination: '%kernel.root_dir%/../public/uploads/site'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: namer.md5