vich_uploader:
    db_driver: orm
    mappings:
        logo_site:
            uri_prefix:         /uploads/site/logo
            upload_destination: '%kernel.root_dir%/../public/uploads/site/logo'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: namer.md5
        main_picture_site:
            uri_prefix:         /uploads/site/main_picture
            upload_destination: '%kernel.root_dir%/../public/uploads/site/main_picture'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: namer.md5
        post_picture_site:
            uri_prefix:         /uploads/blog/post_picture
            upload_destination: '%kernel.root_dir%/../public/uploads/blog/post_picture'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: namer.md5
