# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  base_host: '%env(BASE_HOST)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  namer.md5:
    class: App\Namer\Md5
    public: true
    tags:
      - { name: namer }

  namer.logo.md5:
    class: App\Namer\DirectoryLogoMd5
    public: true
    tags:
      - { name: namer }

  namer.favicon.md5:
    class: App\Namer\DirectoryFaviconMd5
    public: true
    tags:
      - { name: namer }

  namer.mainPicture.md5:
    class: App\Namer\DirectoryMainPictureMd5
    public: true
    tags:
      - { name: namer }

  namer.blogPostPicture.md5:
    class: App\Namer\DirectoryBlogPostPictureMd5
    public: true
    tags:
      - { name: namer }

  App\Controller\RegistrationController:
    public: true
    arguments:
      $formFactory: '@fos_user.profile.form.factory'